title: heyDipo
description: UI/UX Designer · AI Product Strategist
baseurl: ""
url: "https://heydipo.github.io"

markdown: kramdown
permalink: /journal/:title/

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - .venv
  - Gemfile
  - Gemfile.lock
  - README.md
